SELECT A.HOUR, A.COUNT+NVL(B.COUNT,0) AS COUNT
FROM
(SELECT LEVEL-1 AS HOUR, 0 COUNT
FROM DUAL
CONNECT BY LEVEL<=24) A
LEFT OUTER JOIN
(SELECT TO_NUMBER(TO_CHAR(DATETIME, 'HH24')) HOUR, COUNT(*) AS COUNT
FROM ANIMAL_OUTS 
GROUP BY TO_NUMBER(TO_CHAR(DATETIME, 'HH24')))B
ON A.HOUR = B.HOUR
ORDER BY A.HOUR
