-- 코드 인터넷 일부 참고

-- 0부터 23까지 숫자 다 출력하게 하는 코드
-- 임시 테이블 생성
WITH HOUR AS (
    SELECT LEVEL - 1 AS H
    FROM DUAL
    CONNECT BY LEVEL <= 24
)

SELECT HOUR.H AS HOUR, NVL(COUNT(O.DATETIME), 0) AS COUNT
FROM HOUR
LEFT JOIN ANIMAL_OUTS O 
ON TO_CHAR(O.DATETIME, 'HH24') = HOUR.H
GROUP BY HOUR.H
ORDER BY HOUR.H;
