SELECT B.CATEGORY, SUM(SALES) AS TOTAL_SALES  
FROM BOOK B
INNER JOIN
(SELECT *
FROM BOOK_SALES
WHERE TO_CHAR(SALES_DATE,'YYYY-MM-DD') BETWEEN '2022-01-01' AND '2022-01-31')S
ON B.BOOK_ID = S.BOOK_ID 
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY
;
