SELECT B.ANIMAL_ID, B.NAME
FROM
(SELECT ROWNUM AS RNUM, A.*
FROM 
(SELECT I.ANIMAL_ID, I.NAME, (O.DATETIME-I.DATETIME) AS INSTIME
FROM ANIMAL_INS I 
INNER JOIN ANIMAL_OUTS O
ON I.ANIMAL_ID = O.ANIMAL_ID
ORDER BY INSTIME DESC)A)B
WHERE RNUM<=2;
