SELECT 
    H.HISTORY_ID, 
    FLOOR(
        CASE
            WHEN NUM_DAYS >= 90 THEN C.DAILY_FEE * NUM_DAYS * (1 - DP90.DISCOUNT_RATE / 100)
            WHEN NUM_DAYS >= 30 THEN C.DAILY_FEE * NUM_DAYS * (1 - DP30.DISCOUNT_RATE / 100)
            WHEN NUM_DAYS >= 7 THEN C.DAILY_FEE * NUM_DAYS * (1 - DP7.DISCOUNT_RATE / 100)
            ELSE C.DAILY_FEE * NUM_DAYS
        END
    ) AS FEE
FROM 
    (
        SELECT 
            HISTORY_ID,
            CAR_ID,
            (END_DATE - START_DATE + 1) AS NUM_DAYS
        FROM 
            CAR_RENTAL_COMPANY_RENTAL_HISTORY
    ) H
JOIN 
    CAR_RENTAL_COMPANY_CAR C 
ON 
    H.CAR_ID = C.CAR_ID 
AND 
    C.CAR_TYPE = '트럭'
LEFT JOIN 
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN DP90 
ON 
    DP90.CAR_TYPE = '트럭' 
AND 
    DP90.DURATION_TYPE = '90일 이상'
LEFT JOIN 
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN DP30 
ON 
    DP30.CAR_TYPE = '트럭' 
AND 
    DP30.DURATION_TYPE = '30일 이상'
LEFT JOIN 
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN DP7 
ON 
    DP7.CAR_TYPE = '트럭' 
AND 
    DP7.DURATION_TYPE = '7일 이상'
ORDER BY 
    2 DESC, 
    1 DESC;
