-- 코드를 입력하세요 
SELECT HISTORY_ID, TRUNC(DAILY_FEE*DURATION*(100-NVL(discount_rate,0))/100) FEE
FROM
(SELECT HISTORY_ID, (END_DATE-START_DATE +1) DURATION,
(CASE WHEN (END_DATE-START_DATE +1)<7 THEN '7일 미만'
     WHEN (END_DATE-START_DATE +1) BETWEEN 7 AND 29 THEN '7일 이상'
     WHEN (END_DATE-START_DATE +1) BETWEEN 30 AND 90 THEN '30일 이상'
     ELSE '90일 이상'
END) AS DURATION_TYPE,
(SELECT DAILY_FEE FROM CAR_RENTAL_COMPANY_CAR
 WHERE CAR_ID = H.CAR_ID) AS DAILY_FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
WHERE CAR_ID IN (SELECT CAR_ID
                 FROM CAR_RENTAL_COMPANY_CAR 
                 WHERE CAR_TYPE = '트럭')) A
LEFT OUTER JOIN (SELECT DURATION_TYPE, DISCOUNT_RATE
                 FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
                 WHERE CAR_TYPE='트럭') B
ON A.DURATION_TYPE=B.DURATION_TYPE 
ORDER BY FEE DESC, history_id DESC
;
                
