SELECT H.HISTORY_ID, 
CASE WHEN  H.END_DATE-H.START_DATE+1 >= 7 THEN C.DAILY_FEE*(1-D.DISCOUNT_RATE/100)*(H.END_DATE-H.START_DATE+1)
ELSE C.DAILY_FEE*(H.END_DATE-H.START_DATE+1) END AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON C.CAR_ID = H.CAR_ID
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN D ON C.CAR_TYPE = D.CAR_TYPE
WHERE C.CAR_TYPE = '트럭' 
and D.DURATION_TYPE LIKE
CASE WHEN H.END_DATE-H.START_DATE+1 BETWEEN 7 AND 29 THEN '%7일%'
WHEN H.END_DATE-H.START_DATE+1 BETWEEN 30 AND 89 THEN '%30일%'
WHEN H.END_DATE-H.START_DATE+1 >= 90 THEN '%90일%'
ELSE '%7일%' END
ORDER BY FEE DESC, H.HISTORY_ID DESC;
