SELECT 
    TO_CHAR(OS.SALES_DATE, 'YYYY') AS YEAR,
    TO_NUMBER(TO_CHAR(OS.SALES_DATE, 'MM')) AS MONTH,
    COUNT(DISTINCT OS.USER_ID) AS PURCHASED_USERS,
    ROUND(COUNT(DISTINCT OS.USER_ID) / (SELECT COUNT(USER_ID) FROM USER_INFO WHERE TO_CHAR(JOINED, 'YYYY') = '2021'), 1) AS PURCHASED_RATIO
FROM 
    USER_INFO UI
INNER JOIN 
    ONLINE_SALE OS ON UI.USER_ID = OS.USER_ID
    AND TO_CHAR(UI.JOINED, 'YYYY') = '2021'
GROUP BY 
    TO_CHAR(OS.SALES_DATE, 'YYYY'),
    TO_NUMBER(TO_CHAR(OS.SALES_DATE, 'MM'))
ORDER BY 
    1,2;
