SELECT 
    TO_CHAR(S.SALES_DATE, 'YYYY') AS YEAR, 
    TO_NUMBER(TO_CHAR(S.SALES_DATE, 'MM')) AS MONTH, 
    COUNT(DISTINCT S.USER_ID) AS PURCHASED_USERS, 
    ROUND(
        COUNT(DISTINCT(S.USER_ID)) / 
        (SELECT COUNT(DISTINCT(USER_ID)) FROM USER_INFO WHERE TO_CHAR(JOINED, 'YYYY') = '2021'), 1) AS PURCHASED_RATIO
FROM 
    USER_INFO U 
JOIN
    ONLINE_SALE S ON U.USER_ID = S.USER_ID
WHERE U.USER_ID IN (
    SELECT USER_ID
    FROM USER_INFO 
    WHERE TO_CHAR(JOINED, 'YYYY') = '2021'
)   
GROUP BY 
    TO_CHAR(S.SALES_DATE, 'YYYY'), 
    TO_NUMBER(TO_CHAR(S.SALES_DATE, 'MM'))
ORDER BY 
    YEAR, 
    MONTH;
