SELECT 
    C.CAR_ID, 
    C.CAR_TYPE, 
    TRUNC((C.DAILY_FEE * 30) * (1 - NVL(D.DISCOUNT_RATE, 0) / 100)) AS FEE
FROM 
    CAR_RENTAL_COMPANY_CAR C JOIN 
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN D 
ON 
    C.CAR_TYPE = D.CAR_TYPE AND D.DURATION_TYPE = '30일 이상'
WHERE 
    C.CAR_TYPE IN ('SUV', '세단')
    AND C.CAR_ID NOT IN (
        SELECT 
            H.CAR_ID 
        FROM 
            CAR_RENTAL_COMPANY_RENTAL_HISTORY H 
        WHERE 
            H.START_DATE <= TO_DATE('2022-11-30', 'YYYY-MM-DD')
            AND H.END_DATE >= TO_DATE('2022-11-01', 'YYYY-MM-DD')
    )
    AND (C.DAILY_FEE * 30) * (1 - NVL(D.DISCOUNT_RATE, 0) / 100) BETWEEN 500000 AND 2000000
ORDER BY 
    3 DESC, 
    2, 
    1 DESC;
