SELECT DISTINCT(C.CAR_ID), C.CAR_TYPE, 
       (C.DAILY_FEE * (1-D.DISCOUNT_RATE/100) * 30) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
ON C.CAR_ID = H.CAR_ID
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN D
ON C.CAR_TYPE = D.CAR_TYPE
WHERE C.CAR_TYPE IN ('세단', 'SUV')
    AND C.CAR_ID NOT IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE START_DATE BETWEEN TO_DATE('2022-11-01', 'YYYY-MM-DD') 
        AND TO_DATE('2022-11-30', 'YYYY-MM-DD')
        OR END_DATE BETWEEN TO_DATE('2022-11-01', 'YYYY-MM-DD')
        AND TO_DATE('2022-11-30', 'YYYY-MM-DD')
        OR (START_DATE <= TO_DATE('2022-11-01', 'YYYY-MM-DD')
        AND END_DATE >= TO_DATE('2022-11-30', 'YYYY-MM-DD'))
        )
    AND D.DURATION_TYPE = '30일 이상'
    AND (C.DAILY_FEE * (1-D.DISCOUNT_RATE/100) * 30) BETWEEN 500000 AND 2000000
ORDER BY FEE DESC, C.CAR_TYPE ASC, C.CAR_ID DESC;
