SELECT B.NAME, B.DATETIME 
FROM
(SELECT ROWNUM AS RNUM, A.NAME, A.DATETIME
 FROM
(SELECT *
FROM ANIMAL_INS 
WHERE ANIMAL_ID NOT IN (SELECT ANIMAL_ID FROM ANIMAL_OUTS)
ORDER BY DATETIME)A)B
WHERE B.RNUM <= 3
;
