SELECT CAR_ID, CASE WHEN SUM(AY)>0 THEN '대여중'
                    ELSE '대여 가능'
                END AS AVAILABILITY
FROM (SELECT CAR_ID, 
        CASE 
        WHEN END_DATE<TO_DATE('20221016','YYYYMMDD') THEN 0
        WHEN START_DATE>TO_DATE('20221016','YYYYMMDD') THEN 0
            ELSE 1 
        END AS AY
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY)
GROUP BY CAR_ID
ORDER BY 1 DESC;
