-- 코드를 입력하세요
SELECT DISTINCT(CAR_ID), '대여 가능' AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
MINUS
SELECT DISTINCT(CAR_ID), '대여 가능' AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
WHERE TO_DATE('2022-10-16','YYYY-MM-DD') BETWEEN START_DATE AND END_DATE
UNION ALL
SELECT DISTINCT(CAR_ID), '대여중' AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
WHERE TO_DATE('2022-10-16','YYYY-MM-DD') BETWEEN START_DATE AND END_DATE
ORDER BY CAR_ID DESC
;
