SELECT YEAR, MONTH, GENDER, COUNT(DISTINCT U.USER_ID) AS USERS
FROM USER_INFO U
INNER JOIN
(SELECT USER_ID,  
       TO_CHAR(SALES_DATE, 'YYYY') YEAR, 
       TO_CHAR(SALES_DATE, 'FMMM') MONTH 
FROM ONLINE_SALE)O 
ON U.USER_ID = O.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER;
