SELECT TO_NUMBER(TO_CHAR(O.SALES_DATE, 'YYYY')) as YEAR, 
       TO_NUMBER(TO_CHAR(O.SALES_DATE, 'MM')) as MONTH, 
       U.GENDER, 
       COUNT(DISTINCT U.USER_ID) as USERS
FROM USER_INFO U JOIN ONLINE_SALE O
ON U.USER_ID = O.USER_ID
WHERE U.GENDER IS NOT NULL
GROUP BY TO_NUMBER(TO_CHAR(O.SALES_DATE, 'YYYY')), 
         TO_NUMBER(TO_CHAR(O.SALES_DATE, 'MM')), 
         U.GENDER
ORDER BY YEAR, MONTH, GENDER;
