SELECT FP.PRODUCT_ID, FP.PRODUCT_NAME, SUM(FP.PRICE*FO.AMOUNT)
FROM FOOD_PRODUCT FP INNER JOIN FOOD_ORDER FO ON FP.PRODUCT_ID=FO.PRODUCT_ID
WHERE TO_CHAR(FO.PRODUCE_DATE,'YYYY')='2022' AND TO_CHAR(FO.PRODUCE_DATE,'MM')='05'
GROUP BY FP.PRODUCT_ID, FP.PRODUCT_NAME
ORDER BY 3 DESC, 1;
