-- 코드를 입력하세요
SELECT PRODUCT_ID, PRODUCT_NAME, SUM(SALES) AS TOTAL_SALES
FROM
(SELECT P.PRODUCT_ID, P.PRODUCT_NAME, P.PRICE*O.AMOUNT SALES
FROM FOOD_PRODUCT P 
INNER JOIN FOOD_ORDER O
ON P.PRODUCT_ID = O.PRODUCT_ID
WHERE TO_CHAR(PRODUCE_DATE,'YYYY-MM')='2022-05')
GROUP BY PRODUCT_NAME,PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID 
;
