SELECT FP.CATEGORY,FP.PRICE AS MAX_PRICE,FP.PRODUCT_NAME
FROM FOOD_PRODUCT FP
WHERE (FP.CATEGORY,FP.PRICE) IN 
(SELECT FP.CATEGORY,MAX(FP.PRICE)
 FROM FOOD_PRODUCT FP
GROUP BY FP.CATEGORY) AND FP.CATEGORY IN ( '과자', '국', '김치', '식용유')
ORDER BY MAX_PRICE DESC;
