SELECT UU.USER_ID, UU.NICKNAME, UU.CITY ||' '||UU.STREET_ADDRESS1 ||' '|| UU.STREET_ADDRESS2 AS 전체주소, SUBSTR(TLNO,1,3)||'-'||SUBSTR(TLNO,4,4)||'-'||SUBSTR(TLNO,8,4) AS 전화번호
FROM USED_GOODS_BOARD UB INNER JOIN USED_GOODS_USER UU
ON UU.USER_ID=UB.WRITER_ID
GROUP BY UU.USER_ID, UU.NICKNAME, UU.CITY ||' '||UU.STREET_ADDRESS1 ||' '|| UU.STREET_ADDRESS2,TLNO
HAVING COUNT(UB.WRITER_ID)>=3
ORDER BY UU.USER_ID DESC;
