SELECT TO_NUMBER(TO_CHAR(START_DATE,'MM')) AS MONTH, CAR_ID, COUNT(HISTORY_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN 
    (SELECT CC.CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY CC
    WHERE CC.START_DATE >= TO_DATE('20220801','YYYYMMDD') AND CC.START_DATE < TO_DATE('20221101','YYYYMMDD')
    GROUP BY CC.CAR_ID
    HAVING COUNT(CC.HISTORY_ID)>=5)
    AND START_DATE >= TO_DATE('20220801','YYYYMMDD') AND START_DATE < TO_DATE('20221101','YYYYMMDD')
GROUP BY TO_CHAR(START_DATE,'MM'),CAR_ID
HAVING COUNT(HISTORY_ID)>0
ORDER BY 1 ASC,2 DESC
