SELECT AUTHOR_ID, (SELECT AUTHOR_NAME FROM AUTHOR WHERE AUTHOR_ID = X.AUTHOR_ID)AUTHOR_NAME, CATEGORY, SUM(TOTAL_SALES) TOTAL_SALES
FROM BOOK X
INNER JOIN 
(SELECT B.BOOK_ID, AVG(B.PRICE)*SUM(S.SALES) AS TOTAL_SALES
FROM BOOK B
LEFT JOIN BOOK_SALES S
ON B.BOOK_ID = S.BOOK_ID
WHERE TO_CHAR(S.SALES_DATE, 'YYYY-MM')='2022-01'
GROUP BY B.BOOK_ID) Y
ON X.BOOK_ID = Y.BOOK_ID
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC
