SELECT FLAVOR
FROM (SELECT A.FLAVOR, SUM(A.TOTAL+B.TOTAL)
FROM (SELECT FH.FLAVOR, SUM(FH.TOTAL_ORDER) AS TOTAL
FROM FIRST_HALF FH
GROUP BY FH.FLAVOR) A 
INNER JOIN 
(SELECT J.FLAVOR, SUM(J.TOTAL_ORDER) AS TOTAL 
FROM JULY J
GROUP BY J.FLAVOR) B
ON A.FLAVOR=B.FLAVOR
GROUP BY A.FLAVOR
ORDER BY 2 DESC)
WHERE ROWNUM<=3
