-- 코드를 입력하세요
SELECT FLAVOR
FROM
(SELECT ROWNUM RNUM, FLAVOR
FROM
(SELECT F.FLAVOR, (F.TOTAL_ORDER+J.TOTAL_ORDER) TOTAL_ORDER
FROM
(SELECT FLAVOR, SUM(TOTAL_ORDER) TOTAL_ORDER
FROM FIRST_HALF 
GROUP BY FLAVOR)F
FULL OUTER JOIN
(SELECT FLAVOR, SUM(TOTAL_ORDER) TOTAL_ORDER
FROM JULY  
GROUP BY FLAVOR)J
ON F.FLAVOR = J.FLAVOR
ORDER BY TOTAL_ORDER DESC))
WHERE RNUM <=3
;
