SELECT P.PRODUCT_CODE, NVL((P.PRICE * S.SALES_ALL_AMOUNT),0) AS SALES
FROM PRODUCT P
LEFT JOIN
(SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS SALES_ALL_AMOUNT FROM OFFLINE_SALE GROUP BY PRODUCT_ID) S
ON   P.PRODUCT_ID = S.PRODUCT_ID
ORDER BY SALES DESC
, P.PRODUCT_CODE;
