-- 코드를 입력하세요
SELECT A.APNT_NO, P.PT_NAME, P.PT_NO, D.MCDP_CD, D.DR_NAME, A.APNT_YMD
FROM
(
(SELECT *
FROM APPOINTMENT
WHERE TO_CHAR(apnt_ymd, 'YYYY-MM-DD') = '2022-04-13' AND apnt_cncl_yn = 'N') A
INNER JOIN PATIENT P
ON A.PT_NO = P.PT_NO
INNER JOIN DOCTOR D
ON A.MDDR_ID = D.DR_ID
)
ORDER BY A.APNT_YMD;
